<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Имя *
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($data['nickname'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>
