<a href="/users">Пользователи</a>
<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>

<table>
    <?php foreach ($filteredNames as $key => $value): ?>
        <tr>
            <td>
                ID : <?= $value['user']['id'] ?>;  Nickname : <?= $value['user']['nickname'] ?>;   Email : <?= $value['user']['email'] ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>