<h1>New user</h1>

<form action="/users" method="post">
    <div>
        <label>
            <input type="hidden" name="user[id]" value="<?= htmlspecialchars($user['id']) ?>">
        </label>
    </div>
        <label>
            Nickname
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
    </div>
    <input type="submit" value="Submit">
</form>

